### ISSUE TITLE
Titlebar is not drawing under default windows titlebar

### ISSUE THREAD

**Issue by I6-6-6I** [grassator/win32-window-custom-titlebar#3]
Like it's in title I'm trying to modify GLFW's win32 version, so i just copied and pasted example code in places where it should be , but it does not work exacly the same...
I'm overdrawing client area with vulkan so my title bar is not showing and that is fine, becouse i could just change scissor and viewport for that. The problem is that my custom titlebar is under default windows titlebar and I really don't know how to get rid of this default one...
Well i guess i could learn more about win32 but still.

Anyone some ideas, what i could do wrong ?

**Comment by grassator** [comment]
I'm afraid I'm not much help here. I have successfully modified this code to work Direct2d in one of my applications, but it also a Win32 API that definitely does special things behind the scenes.

**Comment by Chomiczjakub** [comment]
Ok then. I will do the investigation myself i bealive hehe
